version: "3"

services:
  filebeat:
    image: elastic/filebeat:7.9.1
    user: root
    networks:
      - elk
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/config/filebeat.yml
      - ./filebeat/logs:/usr/share/filebeat/logs
    deploy:
      mode: global

networks:
  elk:
    driver: bridge
