version: "3"

services:
  filebeat:
    image: elastic/filebeat:7.9.1
    user: root
    networks:
      - elk
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ../logging_test/logs:/usr/share/filebeat/logs:ro
      # - /var/run/docker.sock:/var/run/docker.sock
      # # This is needed for filebeat to load container log path as specified in filebeat.yml
      # - /var/lib/docker/containers/:/var/lib/docker/containers/:ro

      # # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ro

      # # This is needed for filebeat to load logs for system and auth modules
      # - /var/log/:/var/log/:ro
      # # This is needed for filebeat to load logs for auditd module. you might have to install audit system
      # # on ubuntu first (sudo apt-get install -y auditd audispd-plugins)
      # - /var/log/audit/:/var/log/audit/:ro
    # environment:
    #   - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
    #   - KIBANA_HOST=${KIBANA_HOST:-node1}
    #   - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
    #   - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    # disable strict permission checks
    command: ["--strict.perms=false"]
    deploy:
      mode: global

networks:
  elk:
    driver: bridge

volumes:
  filebeat:

configs:
  fb_config:
    file: ./config/filebeat.yml