# cold node
network.host: _site_
cluster.name: docker
node.name: cold
xpack.license.self_generated.type: trial
discovery.seed_hosts: ['hot','warm', 'cold']
cluster.initial_master_nodes: ['hot']
http.port: 9202
xpack.security.enabled: false
node.roles: [ master, data_cold, data_content]
