# http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts: ["http://localhost:9200"]
path.config: /usr/share/logstash/pipeline
xpack.monitoring.enabled: true
# xpack.monitoring.elasticsearch.username: "elastic"
# xpack.monitoring.elasticsearch.password: "neopower83515567"
# xpack.management.elasticsearch.api_key: "Apikey R21uTUdJOEJvLUoybndRYkl0czQ6TUJRRUZSVmFSX09PVmg3bEdiZWxwUQ=="