filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/filebeat/logs/log-*.log
  fields:
    log_type: "app_logs"
  fields_under_root: true

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ./modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: true

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#================================ Processors =====================================

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""

  - script:
      lang: javascript
      id: "route_to_topic"
      source: >
        function process(event) {
          switch(event.fields.logs_from) {
            case 'api/v2/charging/stop.post.js':
              event.fields.namespace = 'api-v2-charging-stop';
              break;
            case 'api/v2/charging/start.post.js':
              event.fields.namespace = 'api-v2-charging-start';
              break;
            case 'api/v2/charging/set/current.post.js':
              event.fields.namespace = 'api-v2-charging-set-current';
              break;
            default:
              event.fields.topic = 'my_topic_default';
          }
        }

#================================ Outputs =====================================

# -------------------------- console output ------------------------------
# output.console:
#   pretty: true

# -------------------------- pulsar output ------------------------------
output.pulsar:
  url: "pulsar://localhost:6650"
  topic: "persistent://%{[np_system_id]}/%{[namespace]}/%{[level]}"
  # topic: persistent://np01/api-v2-charging-stop/info
  name: np-system
  # Supported level: panic, fatal, error, warn, info, debug, trace
  log_level: info
  # Authentication token
  # token:
  # Authentciation oauth2
  # oauth2:
  #   enabled: false
  #   issuerUrl: ""
  #   privateKey: ""
  #   clientId: ""
  #   audience: ""
  #   scope: ""

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

# processors:
#   - add_host_metadata: ~
#   - add_cloud_metadata: ~